### ISSUE TITLE
Created results are not kept in database

### ISSUE THREAD

**Issue by gautam-prab** [iron-claw-972/scout#6]
Not sure what's going wrong, but creating results does not work.

**Comment by gautam-prab** [comment]
Figured this out - if I enter a negative number, it fails to submit the result but does not notify the user of the error; I'll open up a new issue to tell user why result wasn't submitted.

**Comment by Joshua-Anderson** [comment]
It's more than. It fails whenever I add a goal or obstacle as well.

**Comment by Joshua-Anderson** [comment]
This seems to have fixed itself :confused:
